"""
FORGE RAG Generator — Produce markdown RAG documents from corpus and cluster data.

Reads RULE-stage corpus entries plus cluster statistics and generates a
structured markdown reference document for SYNAPSE's RAG knowledge layer.

Output: rag/skills/houdini21-reference/solaris_patterns_extracted.md

ZERO dependency on hou module. Runs outside Houdini as a pure data transform.

Input:  forge/corpus/ (via CorpusManager) + forge/extraction_data/pattern_clusters.json
Output: rag/skills/houdini21-reference/solaris_patterns_extracted.md
"""

from __future__ import annotations

import json
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Any

from forge.engine.schemas import CorpusStage
from forge.engine.corpus_manager import CorpusManager


# =============================================================================
# Paths
# =============================================================================

_DATA_DIR = Path(__file__).resolve().parent.parent / "extraction_data"
PATTERN_CLUSTERS_PATH = _DATA_DIR / "pattern_clusters.json"
CORPUS_DIR = Path(__file__).resolve().parent.parent / "corpus"
RAG_OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent.parent
    / "rag"
    / "skills"
    / "houdini21-reference"
    / "solaris_patterns_extracted.md"
)


# =============================================================================
# Markdown Generation
# =============================================================================


def _generate_header() -> str:
    """Generate document header."""
    return (
        "# Solaris Patterns — Extracted from Houdini 21 Examples\n"
        "\n"
        "> Auto-generated by FORGE extraction pipeline. Do not edit manually.\n"
        f"> Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}\n"
        "\n"
        "This document contains validated Solaris workflow patterns extracted from\n"
        "Houdini's built-in example files. Patterns are ranked by frequency — the\n"
        "most common patterns represent canonical Solaris workflows that SYNAPSE\n"
        "should prioritize in scene assembly, material assignment, and rendering.\n"
        "\n"
        "---\n"
    )


def _generate_type_frequency_table(clusters: list[dict]) -> str:
    """Generate a table of node type frequencies across all clusters."""
    type_counts: Counter[str] = Counter()
    for cluster in clusters:
        count = cluster.get("count", 1)
        for node_type in cluster.get("node_types", []):
            type_counts[node_type] += count

    if not type_counts:
        return ""

    lines = [
        "\n## Node Type Frequency\n",
        "\n| Node Type | Occurrences | Role |",
        "|-----------|-------------|------|",
    ]

    # Import role inference from clusterer for consistent classification
    try:
        from forge.extractors.pattern_clusterer import _infer_role
    except ImportError:
        def _infer_role(types):
            return "general"

    for node_type, count in type_counts.most_common():
        role = _infer_role([node_type])
        lines.append(f"| `{node_type}` | {count} | {role} |")

    lines.append("")
    return "\n".join(lines)


def _generate_connection_frequency(clusters: list[dict]) -> str:
    """Generate a table of most common node-to-node connections."""
    conn_counts: Counter[tuple[str, str]] = Counter()
    for cluster in clusters:
        count = cluster.get("count", 1)
        node_types = cluster.get("node_types", [])
        connections = cluster.get("connections", [])
        # Build name-to-index map isn't available, so use adjacency from
        # the ordered type list — connections are index-based pairs.
        for conn in connections:
            if isinstance(conn, (list, tuple)) and len(conn) == 2:
                src_idx, dst_idx = conn
                if isinstance(src_idx, int) and isinstance(dst_idx, int):
                    if 0 <= src_idx < len(node_types) and 0 <= dst_idx < len(node_types):
                        pair = (node_types[src_idx], node_types[dst_idx])
                        conn_counts[pair] += count

    if not conn_counts:
        return ""

    lines = [
        "\n## Connection Frequency\n",
        "\n| Source Type | Target Type | Occurrences |",
        "|------------|-------------|-------------|",
    ]

    for (src, dst), count in conn_counts.most_common(30):
        lines.append(f"| `{src}` | `{dst}` | {count} |")

    lines.append("")
    return "\n".join(lines)


def _generate_canonical_patterns(
    rules: list[Any],
    patterns: list[Any],
) -> str:
    """Generate the canonical patterns section from corpus RULE + PATTERN entries."""
    entries = rules + patterns
    if not entries:
        return ""

    lines = [
        "\n## Canonical Solaris Patterns\n",
        "\nPatterns validated through frequency analysis of Houdini example files.\n",
    ]

    # Group by category
    by_category: dict[str, list] = {}
    for entry in entries:
        cat = entry.category if hasattr(entry, "category") else "general"
        by_category.setdefault(cat, []).append(entry)

    for category in sorted(by_category.keys()):
        cat_entries = by_category[category]
        lines.append(f"\n### {category.replace('_', ' ').title()}\n")

        for entry in sorted(cat_entries, key=lambda e: -e.confidence):
            stage_badge = entry.stage.value.upper()
            conf = f"{entry.confidence:.0%}"
            lines.append(f"**[{stage_badge}]** (confidence: {conf}, seen {entry.recurrence_count}x)")
            lines.append(f"> {entry.pattern}")
            if entry.context:
                lines.append(f"> *Context:* {entry.context}")
            lines.append("")

    return "\n".join(lines)


def _generate_cluster_summary(stats: dict) -> str:
    """Generate extraction statistics summary."""
    lines = [
        "\n## Extraction Statistics\n",
        f"- **Total topologies analyzed:** {stats.get('total_topologies', 'N/A')}",
        f"- **Unique clusters:** {stats.get('unique_clusters', 'N/A')}",
        f"- **Common fragments:** {stats.get('common_fragments', 'N/A')}",
        f"- **Largest cluster:** {stats.get('largest_cluster_count', 'N/A')} occurrences",
        f"- **Singleton clusters:** {stats.get('singleton_clusters', 'N/A')}",
    ]

    role_dist = stats.get("role_distribution", {})
    if role_dist:
        lines.append("\n### Role Distribution\n")
        lines.append("| Role | Count |")
        lines.append("|------|-------|")
        for role, count in sorted(role_dist.items(), key=lambda x: -x[1]):
            lines.append(f"| {role} | {count} |")

    lines.append("")
    return "\n".join(lines)


def _generate_fragment_section(fragments: list[dict]) -> str:
    """Generate common fragments section."""
    if not fragments:
        return ""

    lines = [
        "\n## Common Fragments\n",
        "\nReusable node-type subsequences found across multiple topology clusters.\n",
    ]

    for frag in fragments[:20]:  # Top 20
        node_types = frag.get("node_types", [])
        chain = " → ".join(f"`{t}`" for t in node_types)
        occ = frag.get("occurrence_count", 0)
        role = frag.get("role", "general")
        lines.append(f"- **{role}** ({occ}x): {chain}")

    lines.append("")
    return "\n".join(lines)


# =============================================================================
# Pipeline Entry Point
# =============================================================================


def generate_rag(
    corpus_dir: Path | None = None,
    clusters_path: Path | None = None,
    output_path: Path | None = None,
) -> Path:
    """Generate the Solaris patterns RAG document.

    Args:
        corpus_dir: Path to FORGE corpus. Defaults to forge/corpus/.
        clusters_path: Path to pattern_clusters.json.
        output_path: Where to write the markdown. Defaults to standard RAG location.

    Returns:
        Path to the generated markdown file.
    """
    c_dir = corpus_dir or CORPUS_DIR
    c_path = clusters_path or PATTERN_CLUSTERS_PATH
    out = output_path or RAG_OUTPUT_PATH

    # Load cluster data
    cluster_data: dict[str, Any] = {}
    if c_path.exists():
        cluster_data = json.loads(c_path.read_text(encoding="utf-8"))
    clusters = cluster_data.get("clusters", [])
    fragments = cluster_data.get("fragments", [])
    stats = cluster_data.get("stats", {})

    # Load corpus entries
    manager = CorpusManager(c_dir)
    rules = manager.get_all_entries(stage=CorpusStage.RULE)
    patterns = manager.get_all_entries(stage=CorpusStage.PATTERN)

    print(f"Generating RAG document:")
    print(f"  Corpus rules: {len(rules)}")
    print(f"  Corpus patterns: {len(patterns)}")
    print(f"  Clusters: {len(clusters)}")
    print(f"  Fragments: {len(fragments)}")

    # Build document
    sections = [
        _generate_header(),
        _generate_cluster_summary(stats),
        _generate_type_frequency_table(clusters),
        _generate_connection_frequency(clusters),
        _generate_canonical_patterns(rules, patterns),
        _generate_fragment_section(fragments),
    ]

    content = "\n".join(s for s in sections if s)

    # Write
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")

    print(f"\n  Output: {out}")
    print(f"  Size: {len(content)} bytes")

    return out


# =============================================================================
# CLI
# =============================================================================

if __name__ == "__main__":
    import sys

    path = generate_rag()
    print(f"\nRAG document generated: {path}")
    sys.exit(0)
