"""BP4-CRUX USDKNOW: emit the lane report JSON into the scratchpad lanes dir."""
import json, os

LANES = (r"C:/Users/User/AppData/Local/Temp/claude/"
         r"C--Users-User-SYNAPSE--claude-worktrees-bp4-crux/"
         r"a00ff7a0-7b7c-4065-9c79-a29ba9d1bc56/scratchpad/lanes")
EV = "C:/Users/User/SYNAPSE/.claude/worktrees/bp4-crux/harness/battleplan/notes/bp4_crux/usdknow"
os.makedirs(LANES, exist_ok=True)

rep = {
 "lane": "USDKNOW",
 "target": {"branch": "bp4/usdknow", "head": "73905537", "product": "a0cc33b1",
            "base": "28a0e183", "origin_master_at_audit": "3a27d1ff"},
 "checker": {
   "baseline_exit": 0, "promotable_checked": 15, "against_crux_stdout_exit": 0,
   "baseline_result_line": "[check] RESULT: PASS (all 15 promotable rows anchor clean)",
   "stdout_source_line": "[check] stdout source: harness/notes/h22wl/bp4_usdknow/stdout.txt  (86 lines, 0 blocked)",
   "note_86_vs_85": "86 is the checker's count: read().split(newline) on an 85-line file with a trailing newline yields 86 elements. The file is 85 lines. Not a defect.",
   "crux_stdout_source_line": "[check] stdout source: crux_usdknow_out/stdout.txt  (86 lines, 0 blocked)",
   "crux_line_numbers_shifted": False,
   "anchor": EV + "/checker_baseline.txt ; " + EV + "/checker_against_crux_stdout.txt"},
 "rerun": {
   "exit_code": 0, "wall_s": 2.59, "lines": 85,
   "build": "USD 0.26.5 | Houdini 22.0.400 | pref_dir C:/Users/User/OneDrive/Documents/houdini22.0",
   "second_run_exit": 0, "second_run_wall_s": 2.59,
   "self_determinism": "run1 vs run2 differ ONLY in the anon layer id and the mkdtemp dir name",
   "anchor": EV + "/crux_run_meta.txt ; " + EV + "/crux_stdout.txt"},
 "arcs_winners_diff": {
   "per_prim_table": "identical (10 rows, same text AND same line numbers 19-28)",
   "ev_lines": "identical (20 BP4-EV lines, same text AND same line numbers)",
   "payload_counts": "identical (loaded=10 unloaded=1 reloaded=10 dropped=9 ; reference before_unload=10 after_unload=10 ; composed arcs root,payload)",
   "arc_order": "identical (local>inherit>variant>reference>payload>specialize ; composed /Test.intensity = 1.0)",
   "c1_c2": "identical (C.1 spot1 before=2.0 after=2.0 so L138 REFUTED ; C.2 /Obj composed=10.0 so first-added-strongest True)",
   "build_pin": "identical (USD 0.26.5, Houdini 22.0.400, same pref_dir)",
   "whole_file": "IDENTICAL after normalising the anon layer id, the mkdtemp dir name and the absolute usdc path -- 86/86 elements, zero diff hunks",
   "normalisation_applied": ["anon hex id -> anon:<ID>:", "bp4_livrps_<rand> -> bp4_livrps_<TMP>",
                             "backslash -> forward slash", "absolute b6 path -> <USDC>"],
   "anchor": EV + "/diff_arcs_winners.txt"},
 "seed": {
   "ratified": False, "ratified_type": "bool (JSON false, not the string false)", "rows": 22,
   "tiers": {"FIXTURE-VERIFIED": 8, "VERIFIED-RUNTIME": 7, "PROPOSED": 5, "DOC-STATED": 2},
   "promotable": 15,
   "promotable_anchor_check": "15/15 (my own code, against BOTH the builder stdout and my crux stdout -- the arc= and verify tokens are present on the anchored line in both)",
   "doc_anchor_sections_exist": "6/7 resolve to a real blueprint heading; 1/7 (instanceable-false) carries a prose reasoning anchor with no section ref -- the row itself says 'no runtime anchor', so it is declared, not hidden",
   "doc_anchor_detail": {
     "variantset-splattier": "#2.5 EXISTS (blueprint L184)",
     "variantset-physics": "#2.8 EXISTS (L232) and D2.7 IS in the 2.8 body",
     "customdata-worldlabs-provenance": "#2.5 EXISTS (L184)",
     "instanceable-false": "prose anchor, no section ref; blueprint sec 2.5 does contain 'One Marble world = one component'",
     "transforms-baked-not-xform": "#2.5 and #2.7 both EXIST; the sub-ref property1 is not a literal string -- it means item 1 of the numbered Performance-properties list in 2.5 (Disk first), which does exist",
     "frame-conversion-order": "#2.7 EXISTS (L221)",
     "payload-heavy-rationale": "#2.5 EXISTS; sub-ref property3 = item 3 of that list (Spherical harmonics are the payload, ~360 MB at 2M), which exists and supports the row"},
   "anchor": EV + "/anchor_verify.txt"},
 "decision_record": {
   "choices_covered": "8/8",
   "arc_named": "8/8", "failure_prevented": "8/8", "tier_stated": "8/8",
   "why_not_each_neighbour_enumerated": "7/8 (2.4 states a LIVRPS reason but delegates neighbour rejection to 2.3 rather than enumerating its own)",
   "stdout_citations": "23 distinct stdout lines cited across the record (40 occurrences with ranges expanded); ALL 23 resolve non-blank on BOTH the builder stdout and my crux stdout, with identical text",
   "section_3_demo": "present -- 'The demo layer (blueprint sec.4) adds no composition arc'; cites Beat 3 and Fallback F-1, ties back to 2.1/2.2/2.5/2.8",
   "rows": [
     {"section": "2.1", "choice": "payload for splat + collider", "arc": "payload",
      "livrps_why_not": "yes -- not Reference, not Sublayer, not inline authoring",
      "failure_prevented": "payload unpacked in memory",
      "tier": "FIXTURE-VERIFIED + VERIFIED-RUNTIME + DOC-STATED",
      "anchors": "stdout.txt:60,46,43,44 -- all resolve on my run"},
     {"section": "2.2", "choice": "purpose split splat=render collider=proxy", "arc": "local (inherited-down)",
      "livrps_why_not": "yes -- collider not default, not guide; splat not default",
      "failure_prevented": "viewport re-cook + collider bleeding into beauty",
      "tier": "FIXTURE-VERIFIED", "anchors": "stdout.txt:31,32,33 -- all resolve"},
     {"section": "2.3", "choice": "variantSet splatTier full|low", "arc": "variant",
      "livrps_why_not": "yes -- not reference-swap, not two payloads",
      "failure_prevented": "stack recomposition per LOD switch; component overriding the shot",
      "tier": "PROPOSED", "anchors": "stdout.txt:60,34 -- resolve"},
     {"section": "2.4", "choice": "variantSet physics none|collision", "arc": "variant",
      "livrps_why_not": "PARTIAL -- reason given, neighbours delegated to 2.3",
      "failure_prevented": "permanently sim-encumbered asset; render/sim fork",
      "tier": "PROPOSED (gate G-1)", "anchors": "blueprint sec.9 doc anchor only -- section exists"},
     {"section": "2.5", "choice": "kind = component", "arc": "local (metadata)",
      "livrps_why_not": "yes -- not assembly/group, not absent",
      "failure_prevented": "world not recognised as a model unit",
      "tier": "FIXTURE-VERIFIED", "anchors": "stdout.txt:30 -- resolves"},
     {"section": "2.6", "choice": "customData:worldlabs provenance", "arc": "local (metadata dict)",
      "livrps_why_not": "yes -- not a typed/applied schema, not sidecar-only",
      "failure_prevented": "provenance divorced from the prim; schema collision",
      "tier": "PROPOSED", "anchors": "stdout.txt:35 -- resolves"},
     {"section": "2.7", "choice": "instanceable = false", "arc": "local (metadata flag)",
      "livrps_why_not": "yes -- 3 bullets against true",
      "failure_prevented": "frozen variant selection; blocked shot overrides",
      "tier": "PROPOSED",
      "anchors": "none -- the section states 'a design decision, no runtime anchor'; the seed row adds a prose blueprint reference"},
     {"section": "2.8", "choice": "where metric/ground/chirality transforms live",
      "arc": "local (baked + applied ledger)",
      "livrps_why_not": "yes -- 3 bullets against a live Xform",
      "failure_prevented": "double transform; non-idempotent re-conversion",
      "tier": "PROPOSED + DOC-STATED", "anchors": "blueprint sec.2.7 / WL-API-03 -- section exists"}],
   "anchor": EV + "/decision_record_check.txt ; " + EV + "/decision_record_check2.txt"},
 "acceptance": [
  {"predicate": "decision record covers every sec.2/sec.4 choice with arc + LIVRPS reason + tier + anchor",
   "builder_verdict": "pass", "crux_verdict": "pass",
   "crux_anchor": EV + "/decision_record_check2.txt -- 8/8 sections carry arc + failure-prevented + tier; 7/8 enumerate rejected neighbours (2.4 delegates to 2.3); section 3 covers sec.4; all 23 stdout citations in the record resolve on my own run"},
  {"predicate": "seed JSON parses; every VERIFIED-RUNTIME / FIXTURE-VERIFIED anchor greps; bp4_usdknow_check.py exits 0 on the committed seed",
   "builder_verdict": "pass", "crux_verdict": "pass",
   "crux_anchor": EV + "/checker_baseline.txt (exit 0, 15 promotable rows) + " + EV + "/anchor_verify.txt (my own code: 15/15 pass on BOTH stdouts) + " + EV + "/checker_against_crux_stdout.txt (exit 0 against my independent stdout, same line numbers)"},
  {"predicate": "probe stdout has the per-prim arc listing for b6_wl_component.usdc, the payload round trip counts, and the LIVRPS winner table",
   "builder_verdict": "pass", "crux_verdict": "pass",
   "crux_anchor": EV + "/crux_stdout.txt -- per-prim table with arcs at :18-28, payload round trip loaded=10 unloaded=1 reloaded=10 at :41-43, reference non-unloadable at :45-46, LIVRPS winner table at :53-68; reproduced independently"},
  {"predicate": "no edit under python/synapse/; ratified:false present in the seed",
   "builder_verdict": "pass", "crux_verdict": "pass",
   "crux_anchor": EV + "/diff_scope.txt -- git diff 28a0e183..HEAD -- python/synapse/ = 0 bytes; git diff origin/master..HEAD -- python/synapse/ = 0 bytes; 7 files, all added, all under harness/ or docs/; mcp_server.py, shared/, tests/, src/ untouched; seed ratified is JSON false (bool)"}],
 "mutations": [
  {"id": "USDKNOW-M1",
   "description": "strip an anchor -- row kind-component anchor stdout.txt:30 -> 'probe Part A'",
   "check_reddened": "python harness/battleplan/notes/bp4_usdknow_check.py",
   "result": "REDDENED",
   "evidence": "exit 1 -- [check] FAIL 'kind-component' tier='FIXTURE-VERIFIED' anchor='probe Part A' -> no stdout.txt:<line> anchor",
   "restored_green": True},
  {"id": "USDKNOW-M2a",
   "description": "promote a PROPOSED row -- instanceable-false PROPOSED -> VERIFIED-RUNTIME, keeping its prose reasoning anchor",
   "check_reddened": "same", "result": "REDDENED",
   "evidence": "exit 1 -- FAIL 'instanceable-false' tier='VERIFIED-RUNTIME' -> no stdout.txt:<line> anchor",
   "restored_green": True},
  {"id": "USDKNOW-M2b",
   "description": "promote a PROPOSED row -- variantset-splattier PROPOSED -> FIXTURE-VERIFIED, keeping its blueprint #2.5 doc anchor",
   "check_reddened": "same", "result": "REDDENED",
   "evidence": "exit 1 -- FAIL 'variantset-splattier' tier='FIXTURE-VERIFIED' anchor='...#2.5' -> no stdout.txt:<line> anchor",
   "restored_green": True},
  {"id": "USDKNOW-M2c",
   "description": "promote a DOC-STATED row -- frame-conversion-order DOC-STATED -> VERIFIED-RUNTIME",
   "check_reddened": "same", "result": "REDDENED",
   "evidence": "exit 1 -- FAIL 'frame-conversion-order' tier='VERIFIED-RUNTIME' -> no stdout.txt:<line> anchor",
   "restored_green": True},
  {"id": "USDKNOW-M3",
   "description": "change the arc on a VERIFIED row -- livrps-reference-over-payload reference -> payload",
   "check_reddened": "same", "result": "REDDENED",
   "evidence": "exit 1 -- FAIL anchor='stdout.txt:66' -> stdout.txt:66 does not carry 'arc=payload' (arc mismatch)",
   "restored_green": True},
  {"id": "USDKNOW-M3b",
   "description": "change the arc on a FIXTURE row -- variantsets-absent-in-sop-build variant -> local",
   "check_reddened": "same", "result": "REDDENED",
   "evidence": "exit 1 -- FAIL -> stdout.txt:34 does not carry 'arc=local' (arc mismatch)",
   "restored_green": True},
  {"id": "USDKNOW-M4",
   "description": "ratified false -> true",
   "check_reddened": "same", "result": "REDDENED",
   "evidence": "exit 1 -- [check] FAIL: seed 'ratified' must be exactly false, got True (rule D-1)",
   "restored_green": True},
  {"id": "USDKNOW-M5",
   "description": "anchor a promotable row at a BLANK line -- purpose-collider-proxy -> stdout.txt:2",
   "check_reddened": "same", "result": "REDDENED",
   "evidence": "exit 1 -- FAIL -> stdout.txt:2 is blank", "restored_green": True},
  {"id": "USDKNOW-M5b",
   "description": "anchor past the end -- purpose-render-scope -> stdout.txt:9999",
   "check_reddened": "same", "result": "REDDENED",
   "evidence": "exit 1 -- FAIL -> line 9999-9999 out of range 1..86", "restored_green": True},
  {"id": "USDKNOW-M5c",
   "description": "point a row at a real but WRONG evidence line -- livrps-specialize-weakest 68 -> 67",
   "check_reddened": "same", "result": "REDDENED",
   "evidence": "exit 1 -- FAIL -> stdout.txt:67 does not carry 'arc=specialize'", "restored_green": True},
  {"id": "USDKNOW-M9",
   "description": "BLOCKED-section guard -- synthetic stdout with the probe's own '[A] BLOCKED: ...' sentence substituted at line 13, line numbers preserved, run via --stdout",
   "check_reddened": "python harness/battleplan/notes/bp4_usdknow_check.py --stdout crux_usdknow_out/stdout_blocked_synthetic.txt",
   "result": "REDDENED",
   "evidence": "exit 1 -- 6 FAILs, all 6 Part-A rows: 'stdout.txt:30..35 is inside a BLOCKED/Traceback section'; 25 blocked lines detected",
   "restored_green": True},
  {"id": "USDKNOW-M6",
   "description": "ADVERSARIAL prefix -- arc 'specialize' -> 'spec' on livrps-specialize-weakest. Line 68 literally reads arc=specialize, so the needle arc=spec substring-matches an arc name that does not exist in USD",
   "check_reddened": "same", "result": "SURVIVED",
   "evidence": "exit 0, RESULT: PASS -- the checker uses (arc_needle in line), so any PREFIX of the real arc passes. A seed row can name a non-existent arc and stay green.",
   "restored_green": True},
  {"id": "USDKNOW-M7",
   "description": "ADVERSARIAL inversion -- verify 'reference_unloadable=False' -> 'unloadable=True' on payload-vs-reference-unloadable. Line 46 contains payload_unloadable=True, so the semantically INVERTED token substring-matches",
   "check_reddened": "same", "result": "SURVIVED",
   "evidence": "exit 0, RESULT: PASS -- the row would then assert the opposite of what it proves and the gate stays green. Sharpest of the three: the verify token is the row's only binding to its meaning.",
   "restored_green": True},
  {"id": "USDKNOW-M8",
   "description": "ADVERSARIAL wrong value -- verify 'dropped=9' -> 'loaded=1' on payload-splat-collider. Line 43 reads loaded=10, so the false claim loaded=1 substring-matches",
   "check_reddened": "same", "result": "SURVIVED",
   "evidence": "exit 0, RESULT: PASS -- a numeric claim can be truncated to a wrong-but-prefixing value and stay green.",
   "restored_green": True}],
 "discrepancies": [
  {"id": "D-1", "severity": "medium",
   "claim_audited": "the checker gates the seed's promotable rows against the probe evidence",
   "finding": "The checker's arc and verify matching is bare SUBSTRING containment. Three mutations that make a row assert something FALSE survive green: arc specialize->spec (M6), verify reference_unloadable=False -> unloadable=True (M7, a semantic inversion), verify dropped=9 -> loaded=1 (M8, a wrong number). The 10 mutation classes the leg claims ARE caught; this is an unclaimed hole, not a broken claim.",
   "fix": "match on token boundaries -- require whitespace or line-edge around the needle, or split the line on whitespace and compare whole tokens.",
   "anchor": EV + "/mutations.txt (M6/M7/M8)"},
  {"id": "D-2", "severity": "medium",
   "claim_audited": "the probe reproduces in a fresh checkout; the missing-fixture path degrades Parts A/B to BLOCKED",
   "finding": "The probe's CANDIDATES list hardcodes the absolute path C:/Users/User/SYNAPSE/.claude/worktrees/bp3-probe/... as candidate 3. With BP4_WL_USDC UNSET and argv pointing at a nonexistent file, the probe still found the fixture and produced output byte-identical (normalised) to the env-set run. Two consequences: (a) the BLOCKED degradation path is UNREACHABLE on this host, so no real run has ever exercised it -- I tested the checker's BLOCKED guard synthetically instead (M9, it fires); (b) 'ran it in a fresh checkout' is not evidence of self-containment -- the probe reaches outside the checkout into a sibling worktree, and on a machine without bp3-probe the reproduction breaks in a way this host cannot show.",
   "anchor": EV + "/probe_selffind_finding.txt ; " + EV + "/crux_stdout_no_env.txt"},
  {"id": "D-3", "severity": "low",
   "claim_audited": "the decision record gives, per choice, the LIVRPS reason why not each neighbour arc",
   "finding": "Section 2.4 (physics variant) gives a LIVRPS reason FOR variant but does not enumerate rejected neighbours; it delegates with 'Same authority argument as 2.3'. Every other section (2.1, 2.2, 2.3, 2.5, 2.6, 2.7, 2.8) enumerates 2-3 explicitly rejected alternatives. Defensible as written, and the thinnest section in the record.",
   "anchor": EV + "/decision_record_check2.txt"},
  {"id": "D-4", "severity": "low",
   "claim_audited": "the decision record covers every choice with an anchor",
   "finding": "No committed gate checks the decision record's own citations. bp4_usdknow_check.py reads only the seed JSON; the record's 23 distinct stdout.txt:N citations (40 occurrences) are ungated. I verified all 23 myself against both stdouts -- zero problems -- but nothing in the tree would catch it if one drifted.",
   "anchor": EV + "/decision_record_check.txt"},
  {"id": "D-5", "severity": "low",
   "claim_audited": "the fixture is a valid one-component world (record 2.5: 'it IS the leaf model')",
   "finding": "b6_wl_component.usdc authors kind=component on TWO NESTED prims: /wl_import AND /wl_import/WL_fixture. USD's model hierarchy rejects the inner one -- I measured IsModel()=False and IsComponent()=False on /wl_import/WL_fixture, and Stage.Traverse(Usd.PrimIsModel) yields exactly 1 prim. The decision record's section 1 table shows both prims carrying kind=component (stdout.txt:20 and :21) but does not flag the nesting; the seed's kind-component row anchors line 30, which reports only the FIRST component found. The 'one queryable unit' behaviour section 2.5 relies on holds here by accident of a malformed hierarchy, not by design -- if a later authoring step makes /wl_import a group or assembly, the model walk would start returning WL_fixture too.",
   "anchor": EV + "/crux_modelhierarchy_stdout.txt (my own probe: " + EV + "/crux_modelhierarchy_probe.py)"},
  {"id": "D-6", "severity": "informational",
   "claim_audited": "stdout.txt is 85 lines (brief) vs the checker reporting 86",
   "finding": "Both are right. The file is 85 lines; the checker splits on newline and gets 86 elements because of the trailing newline, and reports that count. The extra element is empty, so an anchor at 86 would be caught as blank. No defect.",
   "anchor": EV + "/checker_baseline.txt"},
  {"id": "D-7", "severity": "informational",
   "claim_audited": "receipt acceptance-4 evidence 'git diff master..HEAD -- python/synapse/ empty'",
   "finding": "There is no local master branch in a --branch shared clone, so that exact command would fail there. The substance holds: I ran it against origin/master (3a27d1ff) and against the base 28a0e183 -- both 0 bytes.",
   "anchor": EV + "/diff_scope.txt"}],
 "findings": [
  {"id": "CX-1",
   "text": "The probe reproduces exactly. My independent run in a fresh scratch clone with my own out dir produced a stdout IDENTICAL to the builder's after normalising only the anonymous layer id, the mkdtemp directory name and the absolute fixture path -- same 86 elements, zero diff hunks, and crucially the SAME LINE NUMBERS, so every seed anchor still lands on its evidence. The checker exits 0 against my stdout as well as the committed one. Two runs of my own differ only in the anon id and temp dir.",
   "anchor": EV + "/diff_arcs_winners.txt"},
  {"id": "CX-2",
   "text": "All 15 promotable seed rows verify under my own code, independently of the builder's checker, against BOTH stdouts. All 23 stdout citations in the decision record and all 23 in the receipt resolve non-blank with identical text on my run.",
   "anchor": EV + "/anchor_verify.txt ; " + EV + "/receipt_citation_check.txt"},
  {"id": "CX-3",
   "text": "The gate is real for every mutation class the leg claims, and for four more I added. 11 of 14 mutations reddened: strip anchor, promote PROPOSED (two variants), promote DOC-STATED, change arc on a VERIFIED row, change arc on a FIXTURE row, flip ratified, blank-line anchor, out-of-range anchor, wrong-but-real evidence line, and an anchor inside a BLOCKED section.",
   "anchor": EV + "/mutations.txt ; " + EV + "/mutation_M9_blocked_guard.txt"},
  {"id": "CX-4",
   "text": "The gate's binding is substring, not token. Three adversarial mutations survive green while making a row assert something false -- see discrepancy D-1. This is the one place a future editor could quietly wrong a promoted row without the gate noticing.",
   "anchor": EV + "/mutations.txt"},
  {"id": "CX-5",
   "text": "F-1, F-2 and F-3 all hold on my independent run. F-1: the splat Points prim authors purpose=default and computes render (my line 33). F-2: 0 variant sets and customData keys ['userDocBrief'] only (my lines 34, 35). F-3: composition-deep-dive.md line 138 reads verbatim '# If base changes to intensity=0.5, spot1 gets 0.5 (base is stronger)   <- SEE CTO NOTE AT TOP: this line is wrong' and my C.1 run shows spot1 before=2.0 after=2.0, refuting it; line 201 reads verbatim 'inherits.AddInherit(/classes/A)    # First added = strongest inherit   <- unverified, see CTO note' and my C.2 run composes 10.0, confirming it. Context worth stating: both lines were ALREADY flagged by the CTO note at the head of that skill file. The probe's contribution is turning 'wrong per USD semantics (asserted)' into 'refuted on 22.0.400 (measured)' and 'unverified' into 'confirmed'. The decision record says exactly that; the receipt's F-3 wording does not mention the pre-existing flag, which slightly overstates novelty.",
   "anchor": EV + "/findings_spotcheck.txt"},
  {"id": "CX-6",
   "text": "New finding the builder did not surface: the fixture has a component nested inside a component and USD drops the inner one from the model hierarchy. See discrepancy D-5.",
   "anchor": EV + "/crux_modelhierarchy_stdout.txt"},
  {"id": "CX-7",
   "text": "Diff scope is clean and minimal. 7 files, every one an addition, every one under harness/ or docs/. Zero bytes of diff under python/synapse/ against both the base and current origin/master. mcp_server.py, shared/, tests/ and src/ untouched. ratified is a JSON boolean false, not a string.",
   "anchor": EV + "/diff_scope.txt"}],
 "artifacts": [
  EV + "/crux_stdout.txt", EV + "/crux_stdout_run2.txt", EV + "/crux_stdout_no_env.txt",
  EV + "/crux_run_meta.txt", EV + "/checker_baseline.txt", EV + "/checker_against_crux_stdout.txt",
  EV + "/diff_arcs_winners.py", EV + "/diff_arcs_winners.txt",
  EV + "/anchor_verify.py", EV + "/anchor_verify.txt",
  EV + "/decision_record_check.py", EV + "/decision_record_check.txt",
  EV + "/decision_record_check2.py", EV + "/decision_record_check2.txt",
  EV + "/diff_scope.txt", EV + "/findings_spotcheck.txt",
  EV + "/mutations.py", EV + "/mutations.txt", EV + "/mutation_M9_blocked_guard.txt",
  EV + "/probe_selffind_finding.txt", EV + "/receipt_citation_check.txt",
  EV + "/crux_modelhierarchy_probe.py", EV + "/crux_modelhierarchy_stdout.txt",
  EV + "/scratch_final_status.txt"],
 "scratch_status_clean": True,
 "scratch_status_detail": "git status --short in the scratch clone shows only the untracked crux_usdknow_out/ dir I created; git diff --stat HEAD is empty (no tracked change); HEAD still 73905537; final checker re-run exit 0. Seed sha256 6bf80ce31311c4468d6d1dfce2903e98ff4ae668c9f30fa685950b7387c086f9 asserted byte-identical after every one of the 13 seed mutations.",
 "crux_worktree_status": "git status --short in bp4-crux shows only the untracked evidence dir harness/battleplan/notes/bp4_crux/ -- nothing else written, nothing edited",
 "verdict": "PASS with findings -- all four acceptance predicates independently confirmed; the probe reproduces line-for-line; the gate catches every claimed mutation class plus four more; two medium findings (substring matching in the checker, hardcoded fixture path making the BLOCKED path unreachable) and one new fixture finding (nested kind=component) are recorded, none of which falsifies a builder claim."
}

path = os.path.join(LANES, "USDKNOW.json")
with open(path, "w", encoding="utf-8") as fh:
    json.dump(rep, fh, indent=2)
print("wrote", path, os.path.getsize(path), "bytes")
json.load(open(path, encoding="utf-8"))
print("re-parses OK")
